const UserErrorMessage = {
  USER_ERROR_EMAIL_HAS_BEEN_REGISTERED: 'USER_ERROR_EMAIL_HAS_BEEN_REGISTERED',
  USER_ERROR_ACCOUNT_HAS_BEEN_REGISTERED:
    'USER_ERROR_ACCOUNT_HAS_BEEN_REGISTERED',
  USER_ERROR_INCORRECT_USERNAME_OR_PASSWORD:
    'USER_ERROR_INCORRECT_USERNAME_OR_PASSWORD',
  USER_ERROR_UNACTIVATED: 'USER_ERROR_UNACTIVATED',
  USER_ERROR_REGISTER_FAILED: 'USER_ERROR_REGISTER_FAILED',
  USER_IS_NOT_EXIST_IN_THE_SYSTEM: 'USER_IS_NOT_EXIST_IN_THE_SYSTEM',
  USER_IS_NOT_EXIST_IN_THE_EMPLOYEES: 'USER_IS_NOT_EXIST_IN_THE_EMPLOYEES',
  USER_IS_NOT_CONTANT_THE_PASSWORD: 'USER_IS_NOT_CONTANT_THE_PASSWORD',
};

const ModuleErrorMessage = {
  MODULE_HAS_BEEN_REGISTERED: 'ERROR_MODULE_HAS_BEEN_REGISTERED',
};

const RoleErrorMessage = {
  ROLE_ERROR_CREATE: 'ROLE_ERROR_CREATE',
  ROLE_ERROR_UPDATE: 'ROLE_ERROR_UPDATE',
  ROLE_ERROR_DELETE: 'ROLE_ERROR_DELETE',
};

module.exports = {
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  ...UserErrorMessage,
  ...RoleErrorMessage,
  ...ModuleErrorMessage,
};
